---
paths:
  model_note: N_1000_example
parameter_space:
  num_epochs: 30
  write_every: 6
  seed: 20
  write_predictions_every: 6
  write_start: 15
  Kuramoto:
    Data:
      synthetic_data:
        num_steps: 1
        training_set_size: 1400
        N: 1000
        sigma: 1e-3
        network:
          type: random
          mean_degree: 40
          graph_props:
            is_directed: False
      dt: 0.02
    NeuralNet:
      num_layers: 5
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: HardSigmoid
      biases:
        default: ~
    Training:
      batch_size: 5
      loss_function:
        name: MSELoss
      true_parameters:
        sigma: 0.0
