# Project information file for the Neural_ABM project
#
# NOTE Any changes to this file need to be registered using the
#      utopya CLI:
#
#         utopya projects register BASE_DIR --info-file path/to/this/file
#
---
project_name: NeuralABM

paths:
  models_dir: models

  # Location of project-level default configurations
  mv_project_cfg: cfg/multiverse_project_cfg.yml
  project_base_plots: cfg/project_base_plots.yml

  # Locations of python-based model plots and tests
  py_plots_dir: model_plots
  py_tests_dir: tests

metadata:
  long_description: Neural agent-based modelling project
  authors:
    - Thomas Gaskin
  license: LGPLv3+
  language: python3
  version: ~
  long_name: ~
  email: ~
  website: ~
  utopya_compatibility: ~
  misc: ~
  requirements: ~
  description: ~

cfg_set_abs_search_dirs: ~
cfg_set_model_source_subdirs: ~
custom_py_modules: ~
output_files: ~
debug_level_updates: ~
framework_name: ~

settings:
  preload_project_py_plots: ~
  preload_framework_py_plots: ~
