# Project information file for the Neural_ABM project
#
# NOTE Any changes to this file need to be registered using the
#      utopya CLI:
#
#         utopya projects register BASE_DIR --info-file path/to/this/file
#
---
project_name: NeuralABM

paths:
  models_dir: models

  # Location of project-level default configurations
  mv_project_cfg: cfg/multiverse_project_cfg.yml
  project_base_plots: cfg/project_base_plots.yml  

  # Locations of python-based model plots and tests
  py_plots_dir: model_plots
  py_tests_dir: tests

metadata:
  description: Neural agent-based modelling project
  authors:
    - Thomas Gaskin
  license: LGPLv3+
  language: python3
