---
paths:
  model_note: UK_power_grid
parameter_space:
  num_epochs: 1000
  write_every: 20
  seed: 2
  write_predictions_every: 20
  write_start: 50
  Kuramoto:
    second_order: true
    Data:
      write_adjacency_matrix: true
      load_from_dir:
        network: data/Kuramoto/UK_power_grid/UK_power_grid_weighted.h5
        eigen_frequencies: /Users/thomasgaskin/utopya_output/Kuramoto/perturbed_data_second_order_weighted/data/uni0/data.h5
        training_data: /Users/thomasgaskin/utopya_output/Kuramoto/perturbed_data_second_order_weighted/data/uni0/data.h5
        copy_data: True
      synthetic_data:
        num_steps: 2
        training_set_size: 400
        sigma: &sigma 0.0
        eigen_frequencies:
          distribution: normal
          parameters:
            mean: 50
            std: 1.25
          time_series: true
      dt: 0.02
      gamma: 3
    NeuralNet:
      num_layers: 5
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: Hardsigmoid
    Training:
      batch_size: 5
      optimizer: Adam
      learning_rate: 0.002
      loss_function:
        name: MSELoss
      true_parameters:
        sigma: *sigma
