# Default settings for the laser
Laser_Cavity:
  # Chromatic dispersion; normal (D < 0) or anomalous (D > 0)
  D: 1
  # Birefringence of the optical fiber
  K: 0.1
  # Standard deviation of the birefringence time series
  K_std: 0
  # Cavity saturation energy
  E0: 1
  # Bandwidth of the gain media (denoted by tau in original code)
  Omega: 0.1
  # Gain strength (pumping)
  g0: 0.3
  # Distributed loss of the fiber laser cavity
  Gamma: 0.2
  # Non-linear coupling parameters, A + B = 1
  A: !expr 1 / 3
  B: !expr 2 / 3

  # Initial values for the angles; these are set as the initial guesses of the neural network
  initial_angles:
    - &alpha_1 !expr 3.14159 / 6
    - &alpha_2 !expr 3.14159 / 6
    - &alpha_3 !expr 3.14159 / 5
    - &alpha_p !expr 3.14159 / 4

  # Roundtrips to complete during initialisation


# Neural network default configuration
NeuralNet:
  num_layers: !is-positive-int 3
  nodes_per_layer:
    default: !is-positive-int 20
  biases:
    default: ~
  activation_funcs:
    default: sigmoid
    layer_specific:
      -1: tanh # Outputs in [-1, 1], which are then multiplied by pi, such that the final output is in [-pi, pi]
  learning_rate: !is-positive 0.002
  prior:
    - distribution: uniform
      parameters:
        lower: *alpha_1
        upper: *alpha_1
    - distribution: uniform
      parameters:
        lower: *alpha_2
        upper: *alpha_2
    - distribution: uniform
      parameters:
        lower: *alpha_3
        upper: *alpha_3
    - distribution: uniform
      parameters:
        lower: *alpha_p
        upper: *alpha_p

Training:
  batch_size: !is-positive-int 2
  device: cpu
  num_threads: ~

  # Scale the infection time by a factor of 10 to ensure all learned parameters are of equal magnitude.
  # This makes training more efficient.
  scaling_factors:
    t_infectious: 10
