---
paths:
  model_note: Large_sample
parameter_space:
  num_epochs: 60
  write_every: 100
  seed: 20
  write_predictions_every: 100
  write_start: 500
  Kuramoto:
    Data:
      synthetic_data:
        num_steps: 2
        training_set_size: 500
        N: 1000
        sigma: &sigma 0.0
        network:
          type: random
          mean_degree: 20
          graph_props:
            is_directed: False
            WattsStrogatz:
              p_rewire: 0.5
        dt: 0.02
    NeuralNet:
      num_layers: 5
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: Hardsigmoid
      biases:
        default: ~
    Training:
      batch_size: 5
      optimizer: Adam
      learning_rate: 0.002
      loss_function:
        name: MSELoss
      true_parameters:
        sigma: *sigma
