paths:
  model_note: ABM_predictions
perform_sweep: true
parameter_space:
  seed: !sweep
    default: 1
    range: [60]
  num_epochs: 100
  write_start: 1
  write_every: 1
  SIR:
    Data:
      load_from_dir: data/SIR/ABM_data/data/uni0/data.h5
    NeuralNet:
      num_layers: 2
      nodes_per_layer:
        default: 20
      prior:
        - distribution: uniform
          parameters:
            lower: 0
            upper: 1
        # tau is scaled by 10
        - distribution: uniform
          parameters:
            lower: 0.1
            upper: 3.1
        - distribution: uniform
          parameters:
            lower: 0
            upper: 0.8
      activation_funcs:
        default: tanh
        layer_specific:
          -1: abs
      learning_rate: 0.002
      optimizer: Adam
    Training:
      batch_size: 100
      to_learn: [p_infect, t_infectious, sigma]
