---
parameter_space:
  num_epochs: 150
  write_predictions_every: -1
  write_every: 1
  seed: 39
  HarrisWilsonNW:
    Data:
      num_training_steps: 500
      training_set_size: 1
      synthetic_data:
        N_origin: 5
        N_destination: 10
        dt: &dt 0.001
        alpha: &alpha 0.8
        beta: &beta 4
        kappa: &kappa 3
        sigma: &sigma 0.0
        epsilon: &epsilon 10
        write_start: 1
        write_every: 1
        num_steps: 1000
        origin_size_std: 0.1
    Training:
      batch_size: 10
      true_parameters:
        alpha: *alpha
        beta: *beta
        kappa: *kappa
        sigma: *sigma
        epsilon: *epsilon
        dt: *dt
      learning_rate: 0.002
    NeuralNet:
      activation_funcs:
        layer_specific:
          -1: HardSigmoid
