---
perform_sweep: true
paths:
  model_note: noisy_training_data_N_100
parameter_space:
  seed: 1
  num_epochs: 0
  write_every: 1
  write_predictions_every: -1
  Kuramoto:
    Data:
      load_from_dir:
        network: /Users/thomasgaskin/utopya_output/Kuramoto/networks/data/N_100_example/data.h5
        eigen_frequencies: /Users/thomasgaskin/utopya_output/Kuramoto/networks/data/N_100_example/data.h5
      synthetic_data:
        num_steps: 10
        training_set_size: 200
        N: 100
        sigma: !sweep
          default: 0.1
          values: [1e-5, 5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 5e-2, 1e-1, 5e-1]
        dt: 0.02
