---
paths:
  model_note: London_dataset
parameter_space:
  num_epochs: 200
  write_predictions_every: 2
  write_every: 2
  write_start: 10
  seed: 39
  HarrisWilsonNW:
    Data:
      num_training_steps: &num_steps 8000
      training_set_size: 1
      load_from_dir:
        origin_zones: &data data/HarrisWilsonNW/London_data.h5
        network: *data
        destination_zones: *data
      synthetic_data:
        dt: &dt 0.001
        alpha: &alpha 0.92
        beta: &beta 0.54
        kappa: &kappa 8.3
        sigma: 0.14
        epsilon: &epsilon 2
        num_steps: *num_steps
        origin_size_std: 0.01
    Training:
      batch_size: 10
      true_parameters:
        alpha: *alpha
        beta: *beta
        kappa: *kappa
        sigma: 0
        epsilon: *epsilon
        dt: *dt
