perform_sweep: true
paths:
  model_note: Predictions
parameter_space:
  seed: !sweep
    default: 1
    range: [50]
  num_epochs: 60
  write_start: 1
  write_every: 1
  SIR:
    Data:
      load_from_dir: data/SIR/ABM_data/data/uni0/data.h5
    NeuralNet:
      num_layers: 3
      nodes_per_layer:
        default: 20
      biases:
        default: ~
      activation_funcs:
        default: sigmoid
        layer_specific:
          -1: abs
      learning_rate: 0.002
      optimizer: Adam

      # Priors on p_infect, t_infectious, sigma.
      # t_infectious is scaled by a factor of 10
      prior:
        - distribution: uniform
          parameters:
            lower: 0
            upper: 1
        - distribution: uniform
          parameters:
            lower: 0.1
            upper: 3.1
        - distribution: uniform
          parameters:
            lower: 0
            upper: 0.8

    Training:
      batch_size: 100
      to_learn: [p_infect, t_infectious, sigma]
