---
perform_sweep: False
paths:
  model_note: Sample_run
parameter_space:
  seed: !sweep
    default: 2
    values: [1, 2]
  num_epochs: 500
  write_every: 10
  write_predictions_every: 20
  Kuramoto:
    Data:
      write_adjacency_matrix: True
      load_from_dir:
        copy_data: True
        network: /Users/thomasgaskin/utopya_output/Kuramoto/network/data/uni0/data.h5
        training_data: /Users/thomasgaskin/utopya_output/Kuramoto/training_data/data/uni7/data.h5
        eigen_frequencies: /Users/thomasgaskin/utopya_output/Kuramoto/network/data/uni0/data.h5
      synthetic_data:
        num_steps: 10
        training_set_size: 20
        N: 16
        sigma: &sigma 0.0
        network:
          type: random
          mean_degree: 6
          graph_props:
            is_directed: False
            WattsStrogatz:
              p_rewire: 0.5
        dt: 0.02
    NeuralNet:
      num_layers: !sweep
        default: 5
        values: [4, 5]
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: Hardsigmoid
      biases:
        default: ~
    Training:
      batch_size: 10
      optimizer: Adam
      learning_rate: 0.002
      loss_function:
        name: MSELoss
      true_parameters:
        sigma: *sigma

