Data:
  synthetic_data:
    N: !is-positive-int 100
    network:
      mean_degree: !is-positive-int 5
      type: !param
        default: random
        dtype: str
        is_any_of: [random, ErdosRenyi, WattsStrogatz, scale-free]
      graph_props:
        is_directed: !is-bool false
        WattsStrogatz:
          p_rewire: !is-probability 0.2

    epsilon: !is-in-unit-interval &epsilon 0.3
    mu: !is-in-unit-interval &mu 0.3
    sigma: !is-positive-or-zero &sigma 0.5
    num_steps: !is-positive-int 60

# Neural net configuration
NeuralNet:
  num_layers: !is-positive-int 1
  nodes_per_layer: !is-positive-int 20
  activation_funcs:
    -1: sigmoid
  bias: !is-bool True
  init_bias: [0, 1]
  learning_rate: !is-positive 0.002

Training:
  batch_size: !is-positive-int 1
  to_learn: [ network ]
  true_parameters:
    epsilon: *epsilon
    mu: *mu
    sigma: *sigma

# Whether to write out the training time
write_time: False

