---
paths:
  model_note: Sample_run
parameter_space:
  seed: 0
  num_epochs: 6
  write_start: 1
  write_every: 1
  HarrisWilson:
    Data:
      load_from_dir: data/HarrisWilson/synthetic_data/noiseless/N_1000_M_100

    # Settings for the neural net architecture
    NeuralNet:
      num_layers: 1
      nodes_per_layer:
        default: 20
      activation_funcs:
        layer_specific:
          -1: abs
      biases:
        default: [ 0, 4 ]
      learning_rate: 0.002
      optimizer: Adam

    # Settings for the neural net training
    Training:
      to_learn: [ alpha, beta, kappa ]
      batch_size: 1
      true_parameters:
        sigma: 0
