paths:
  model_note: Hyperparameters_biases
perform_sweep: True
parameter_space:
  seed: 1
  num_epochs: 4000
  write_start: 1
  write_every: 10
  SEIRD+:
    Data:
      load_from_dir: data/SEIRD_Berlin_data/March_to_Oct.h5
      time_dependent_params:
        k_E:
          - [ 0, 40 ]
          - [ 40, 80 ]
          - [ 80, 120 ]
          - [ 120, ~ ]
        k_SY:
          - [ 0, 40 ]
          - [ 40, 80 ]
          - [ 80, 120 ]
          - [ 120, ~ ]
      synthetic_data:
        dt: 0.1
        k_I: 0.09
        k_S: 0.192
        k_H: 0.015
        k_C: 0.174
        k_R: 0.033
        k_D: 0.258
        k_CT: 10
      training_data_size: !slice [0, 200]
    NeuralNet:
      num_layers: 3
      nodes_per_layer:
        default: 20
      biases:
        default: !sweep
          default: [0, 1]
          values: [[0, 1], [0, 2], [0, 4], [0, 6]]
          name: bias
      activation_funcs:
        default: sigmoid
        layer_specific:
          -1: abs
      learning_rate: 0.002
      optimizer: Adam
    Training:
      batch_size: 200
      BERLIN_data_loss: True
