paths:
  model_note: MCMC
perform_sweep: True
parameter_space:
  seed: !sweep
    default: 1
    range: [50]
  num_epochs: 0
  write_start: 1
  write_every: 1
  SIR:
    NeuralNet:
      prior: ~
    Data:
      load_from_dir: data/SIR/true_data_grid_search/data.h5
    Training:
      to_learn: [p_infect, t_infectious, alpha]
      true_parameters:
        sigma: 0
    MCMC:
      perform_sampling: True
      write_start: 10
      n_samples: 50
      write_every: 1
      batch_size: 100
      lr: 0.02
      prior:
        - distribution: uniform
          parameters:
            lower: 0
            upper: 1
        - distribution: uniform
          parameters:
            lower: 0.033
            upper: 1.033
        - distribution: uniform
          parameters:
            lower: 0
            upper: 1
