Data:
  synthetic_data:
    type: from_ABM
    N: !is-positive-int 150
    space: [10, 10]
    is_periodic: !is-bool false
    r_infectious: !is-positive 1.0
    p_infect: !is-probability 0.5
    t_infectious: !is-positive 30
    sigma_s: !is-positive-or-zero 0.15
    sigma_i: !is-positive-or-zero 0.03
    sigma_r: !is-positive-or-zero 0.15
    num_steps: 200

NeuralNet:
  num_layers: !is-positive-int 1
  nodes_per_layer:
    default: !is-positive-int 20
  biases:
    default: [0, 1]
  activation_funcs:
    default: linear
    layer_specific:
      -1: abs
  learning_rate: !is-positive 0.002

Training:
  batch_size: !is-positive-int 1
  loss_function:
    name: MSELoss
  to_learn: [ p_infect, t_infectious, sigma ]
  device: cpu
  num_threads: ~
