---
paths:
  model_note: Regression
perform_sweep: True
parameter_space:
  seed: !sweep
    default: 0
    range: [5]
  num_epochs: 500
  write_every: 10
  write_predictions_every: -1
  perform_regression: true
  Kuramoto:
    Data:
      write_adjacency_matrix: True
      synthetic_data:
        num_steps: 5
        training_set_size: 10
        N: 16
        sigma: !sweep
          default: 0
          values: [1e-6, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 2e-2, 4e-2, 6e-2, 8e-2, 1e-1]
        network:
          type: random
          mean_degree: 6
          graph_props:
            is_directed: False
            WattsStrogatz:
              p_rewire: 0.5
        dt: 0.01
    NeuralNet:
      num_layers: 5
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: Hardsigmoid
      biases:
        default: ~
    Training:
      batch_size: 10
      optimizer: Adam
      learning_rate: 0.002
      loss_function:
        name: MSELoss
      true_parameters:
        sigma: 0

